# Generated by Django 3.2.2 on 2021-05-22 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicmodels', '0002_visit_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='visit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicmodels.visit'),
        ),
    ]
