# Generated by Django 3.2.2 on 2021-05-22 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicmodels', '0003_alter_appointment_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='medic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='medicmodels.medic'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='medicmodels.patient'),
            preserve_default=False,
        ),
    ]
