# Generated by Django 3.2.2 on 2021-05-23 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicmodels', '0004_auto_20210522_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='visit',
        ),
        migrations.AddField(
            model_name='visit',
            name='appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicmodels.appointment'),
        ),
    ]
